# Generated by Django 3.2.5 on 2022-05-22 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0003_response'),
    ]

    operations = [
        migrations.AddField(
            model_name='response',
            name='active',
            field=models.BooleanField(default=False),
        ),
    ]
