# Generated by Django 3.2.5 on 2022-05-26 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_auto_20220525_0209'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='postal_code',
            field=models.CharField(default='', max_length=20, verbose_name='Почтовый индекс'),
        ),
    ]
